# Generated by Django 3.1.4 on 2020-12-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfgc_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
